server:
  port: ${PORT}

spring:
  application:
    name: identity-service

  # App uses R2DBC for non-blocking I/O
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 20

  # Flyway migrations use JDBC
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

logging:
  level:
    org.springframework.security: INFO
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info