server:
  port: ${PORT}

spring:
  application:
    name: identity-service

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 20

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

logging:
  level:
    org.springframework.security: INFO
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.flywaydb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info